### ISSUE TITLE
Fecha de TP1

### ISSUE THREAD

**Issue by valenpontaut** [algoritmos-rw/tda_bg#19]
En el calendario completo aparece fecha de entrega del TP1 para el 8/4 y en la sección "TPs" de la página aparece fecha de entrega para el 4/4

**Comment by mbuchwald** [comment]
Buenas! Esto se corrigió [acá](https://github.com/algoritmos-rw/tda_bg/commit/0e4ce0014d21f39e026b9e6a8a6cda615b9f9054)
